name: supplychain

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "17 7 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  source:
    uses: noeljackson/supplychain/.github/workflows/scan.yml@dd34170a75a80d9b3484e39df0ac2a5ebf6682dc
    with:
      policy: strict
